basePath: /api/v1
definitions:
  models.Portfolio:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      isActive:
        type: boolean
      isFinance:
        type: boolean
      isInternal:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
    type: object
  requests.CreatePortfolioRequest:
    properties:
      isActive:
        type: boolean
      isFinance:
        type: boolean
      isInternal:
        type: boolean
      name:
        maxLength: 20
        type: string
    required:
    - name
    type: object
  requests.UpdatePortfolioRequest:
    properties:
      id:
        type: integer
      isActive:
        type: boolean
      isFinance:
        type: boolean
      isInternal:
        type: boolean
      name:
        maxLength: 20
        type: string
    required:
    - id
    - name
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Example CRUD API for portfolios entity
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Example CRUD API
  version: "0.1"
paths:
  /portfolios:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Portfolio'
            type: array
      summary: Get portfolios array
      tags:
      - Portfolios
    post:
      parameters:
      - description: Portfolio Body
        in: body
        name: portfolio
        required: true
        schema:
          $ref: '#/definitions/requests.CreatePortfolioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Portfolio'
      summary: Creates portfolio
      tags:
      - Portfolios
    put:
      parameters:
      - description: Portfolio ID
        in: path
        name: id
        required: true
        type: integer
      - description: Portfolio Body
        in: body
        name: portfolio
        required: true
        schema:
          $ref: '#/definitions/requests.UpdatePortfolioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Portfolio'
      summary: Updates portfolio
      tags:
      - Portfolios
  /portfolios/{id}:
    delete:
      description: Deletes portfolio
      parameters:
      - description: Portfolio ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Deletes portfolio by id
      tags:
      - Portfolios
    get:
      parameters:
      - description: Portfolio ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Portfolio'
      summary: Gets portfolio by id
      tags:
      - Portfolios
swagger: "2.0"
